### PR TITLE
Remove outdated todo comment

### PR DESCRIPTION
**Pull request by Niederb**
Extremely proud of this achievement 😄

### CODE REVIEW

**Review by clangenb — COMMENTED** [review]
Ehhhm, I am very proud of you. However, why is this comment obsolete? :)

**Comment by haerdib** [comment]
https://github.com/integritee-network/pallets/issues/56 :P

**Comment by clangenb** [comment]
But IMO the function needs to be removed to.

**Comment by Niederb** [comment]
I think it still makes sense to allow to unregister the enclave (for example we could do it during worker shutdown).

**Comment by clangenb** [comment]
Ok, I agreed 👍

**Pull request merged**
