### PR TITLE
upgrade to Polkadot v0.9.36

### PR DESCRIPTION
**Pull request by Chengcheng-S**
upgrade to polkadot-v0.9.36

- Only bump up to version v0.9.36
- pallet-paratchain onchain method add call_index, pallet-claims & pallet-teerex & pallet-teeracle & pallet-siedchain declared as dev_mode   Related substrate PR  https://github.com/paritytech/substrate/pull/11381
- pallet-claims toml file add `license = "Apache-2.0"`

### CODE REVIEW

**Review by clangenb — APPROVED** [review]
Thanks a lot, looks good to me!

**Comment by clangenb** [comment]
We seem to have two issues here:
1. We have a warning in the CI about deprecated use of a function.
2. We will have to add another accepted licence in the [about.toml](https://github.com/integritee-network/pallets/blob/master/about.toml): Apache-2.0 WITH LLVM-exception

**Comment by Chengcheng-S** [comment]
> We seem to have two issues here:
> 
> 1. We have a warning in the CI about deprecated use of a function.
> 2. We will have to add another accepted licence in the [about.toml](https://github.com/integritee-network/pallets/blob/master/about.toml): Apache-2.0 WITH LLVM-exception

OK~  will fix these errors as soon as possible.

**Review by clangenb — APPROVED** [review]
Nice, looks good to me! I opened an issue for assigning explicit call indexes to the remaining pallet calls: https://github.com/integritee-network/pallets/issues/129

**Comment by Chengcheng-S** [comment]
Thanks!

**Pull request merged**
